import express from 'express';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

// Import the server handler generated by the build
import { default as handler } from './dist/server/index.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const app = express();

// 1. Serve static assets
app.use(express.static(join(__dirname, 'dist/client')));

// 2. Handle SSR requests - the handler is a Node-compatible listener
app.all('*', (req, res) => {
  handler(req, res);
});

const port = process.env.PORT || 3000;
app.listen(port, () => {
  console.log(`🚀 SSR Server running at port ${port}`);
});
