/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CheckerRouteImport } from './routes/checker'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BuilderNewRouteImport } from './routes/builder.new'
import { Route as BuilderIdRouteImport } from './routes/builder.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckerRoute = CheckerRouteImport.update({
  id: '/checker',
  path: '/checker',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderNewRoute = BuilderNewRouteImport.update({
  id: '/builder/new',
  path: '/builder/new',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderIdRoute = BuilderIdRouteImport.update({
  id: '/builder/$id',
  path: '/builder/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checker': typeof CheckerRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/builder/$id': typeof BuilderIdRoute
  '/builder/new': typeof BuilderNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checker': typeof CheckerRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/builder/$id': typeof BuilderIdRoute
  '/builder/new': typeof BuilderNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checker': typeof CheckerRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/builder/$id': typeof BuilderIdRoute
  '/builder/new': typeof BuilderNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checker'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/builder/$id'
    | '/builder/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checker'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/builder/$id'
    | '/builder/new'
  id:
    | '__root__'
    | '/'
    | '/checker'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/builder/$id'
    | '/builder/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckerRoute: typeof CheckerRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  BuilderIdRoute: typeof BuilderIdRoute
  BuilderNewRoute: typeof BuilderNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checker': {
      id: '/checker'
      path: '/checker'
      fullPath: '/checker'
      preLoaderRoute: typeof CheckerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder/new': {
      id: '/builder/new'
      path: '/builder/new'
      fullPath: '/builder/new'
      preLoaderRoute: typeof BuilderNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder/$id': {
      id: '/builder/$id'
      path: '/builder/$id'
      fullPath: '/builder/$id'
      preLoaderRoute: typeof BuilderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckerRoute: CheckerRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  BuilderIdRoute: BuilderIdRoute,
  BuilderNewRoute: BuilderNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
